config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :wikis, :path => "notes"
  resources :contacts, only: [:new, :create]
  resources :charges, only: [:new, :create]
  resources :wikis do
    resources :collaborators, only: [:new, :create, :destroy]
    get :autocomplete_user_email, :on => :collection
    collection do
      get 'search'
    end
  end

  get 'downgrade' => 'users#downgrade'
  get 'about' => 'welcome#about'
  get 'home' => 'welcome#home'
  root to: "welcome#home"
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators
  validates :title, presence: true, length: {minimum: 1 }
  validates :body, presence: true

  def private?
    self.private == true
  end

  def self.find_view(user, wikis)
    @viewable_wikis = []
    wikis.each do |wiki|
      if (wiki.user == user || !wiki.private? || wiki.collaborators.include?(user))
        @viewable_wikis << wiki
      end
    end
  end

  def self.search(params)
    wikis = Wiki.where("title like ? or body like ?", "%#{params[:search]}%", "%#{params[:search]}%") if params[:search].present?
  end

  private

  def make_public
    self.private == false
  end

end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :set_wiki
  autocomplete :user, :email

  def new
    @collaborator = Collaborator.new
  end

  def create
    @collaborator = Collaborator.new(wiki_id: @wiki.id, user_id: params[:user_id])

    if @collaborator.save
      flash[:notice] = "Collaborator has been added."
      redirect_to @wiki
    else
      flash[:error] = "Collaborator was not added."
      render :show
    end
  end

  def destroy
    @collaborator = Collaborator.find(params[:id])

    if @collaborator.destroy
      flash[:notice] = "Collaborator has been removed."
      redirect_to @wiki
    else
      flash[:error] = "Collaborator was not removed."
      render :show
    end
  end

  private

  def set_wiki
    @wiki = Wiki.friendly.find(params[:wiki_id])
  end

end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/views/collaborators/_collaborators.html.erb
<h4>Collaborators</h4>
<ul>
  <% @wiki.collaborators.each do |collaborator| %>
    <li>
      <h4>
        <%= collaborator.user.email %>
        <%= link_to "", "/wikis/#{@wiki.id}/collaborators/#{collaborator.id}", method: :delete, class: 'glyphicon glyphicon-remove' %>
      </h4>
    </li>
  <% end %>
</ul>

app/views/collaborators/_form.html.erb
<% if @wiki.user_id == current_user.id || current_user.admin? %>
		<div class="form-group">
			<% @users.each do |user| %>
				<h4><%= user.email %> </h4>

				<% if @wiki.users.include? user %>
					<div>
					<%= link_to "Remove Collaborator", wiki_collaborator_path(@wiki, @wiki.collaborators.find_by_user_id(user.id).id), method: :delete, class: 'btn btn-danger' %>
				  </div>
				<% else %>
					<div>
					<%= link_to "Add Collaborator", wiki_collaborators_path(@wiki, user_id: user.id), method: :post, class: 'btn btn-info' %>
					</div>
				<% end %>
			<% end %>
		</div>
<% end %>

app/views/collaborators/new.html.erb
<h1>Add Collaborator</h1>
<%= form_for [@wiki] do |f| %>
  <%= collection_check_boxes(:wiki, :user_ids, User.all - [f.object.user], :id, :email) do |u| %>
    <div class="checkbox">
      <%= u.label do %>
        <%= u.check_box %>
        <%= u.object.email %>
      <% end %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>