config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :wikis, :path => "notes"
  resources :contacts, only: [:new, :create]
  resources :charges, only: [:new, :create]
  resources :wikis do
    resources :collaborators, only: [:new, :create, :destroy]
    get :autocomplete_user_email, :on => :collection
    collection do
      get 'search'
    end
  end

  get 'downgrade' => 'users#downgrade'
  get 'about' => 'welcome#about'
  get 'home' => 'welcome#home'
  root to: "welcome#home"
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  #before_filter :authenticate_user!, except: [ :home, :about ]
  def index
  end

  def about
  end

  def home
    if current_user
      @my_wikis = Wiki.where(:user_id => current_user.id).all.limit(5).order('updated_at DESC')
    end
  end
end

app/views/welcome/_my_wikis.html.erb
<div class="col-md-6">
  <% if @my_wikis.empty? %>
    <h2>You don't have any notes.</h2>
    <div class="start-btn"><%= link_to 'Start writing!', new_wiki_path, class: 'btn btn-success' %></div>
  <% else %>
    <h2>Welcome back. Here are your recent notes:</h2>
    <ul>
      <% @my_wikis.each do |wiki| %>
        <li><%= link_to wiki.title, wiki %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/welcome/home.html.erb
<!-- Home banner -->
<section id="banner">
  <div class="wrapper">
    <div class="content">
      <h1 class="title">Share your ideas</h1>
      <h2 class="sub_title">Create public or private notes for you and your friends</h2>
      <% if !current_user %>
        <div class="btn-wrapper">
          <div class="button_wrapper btn btn-info"><%= link_to "Sign in", new_user_session_path %></div>
        </div>
      <% end %>
    </div>
  </div>
</section>

<!-- Main Content -->
<div class="main-content">
  <div class="row">
    <% if current_user && current_user.role == 'standard' %>
        <%= render partial: 'my_wikis' %>
        <div class="col-md-6">
          <h2>Premium accounts for privacy</h2>
          <p>Upgrade to a premium account to keep your notes private, for you and your friends.
          <br>
          <br>
          Choose whoever you want to make your notes available to by adding collaborators.
          <div class="btn btn-warning"><%= link_to "Upgrade to premium", new_charge_path %></div>
          </p>

          <h2>How are you liking noted?</h2>
          <p><%= link_to "Let us know!", new_contact_path %></p>
          <h2>Trying to edit your account?</h2>
          <p>You can do that <%= link_to 'here!', edit_user_registration_path %></p>
        </div>
      </div>

    <% elsif current_user && current_user.role == 'premium' %>
        <%= render partial: 'my_wikis' %>
        <div class="col-md-6">
          <h2>Thanks for being a premium member!</h2>
          <br>
          <h2>How are you liking noted?</h2>
          <p><%= link_to "Let us know!", new_contact_path %></p>
          <h2>Trying to edit your account?</h2>
          <p>You can do that <%= link_to 'here!', edit_user_registration_path %></p>
        </div>
      </div>

    <% elsif current_user && current_user.role == 'admin' %>
      <%= render partial: 'my_wikis' %>

        <div class="col-md-6">
          <h2>How are you liking noted?</h2>
          <p><%= link_to "Let us know!", about_path %></p>
          <h2>Trying to edit your account?</h2>
          <p>You can do that <%= link_to 'here!', edit_user_registration_path %></p>
        </div>
      </div>

    <% else %>
      <div class="col-md-6">
        <h2>Open, free, and collaborative</h2>
        <p>With noted, you can share, write, and publish notes that anybody can contribute to.
        <br>
        <br>
        Once you're signed up, you can upgrade to premium to enjoy all the same features, with added privacy by controlling who can view and contribute to your notes.</p>
      </div>

      <div class="col-md-6">
        <h2>Join today</h2>
        <p>Not a member? Sign up now and start sharing your notes!</p>
        <div class="button_wrapper btn btn-info"><%= link_to "Sign up for free", new_user_registration_path %></div>
        </div>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="container">

  <header class="bg-primary text-white">
    <div class="container text-center">
      <h1>noted</h1>
      <h2>An open community to share knowledge</h2>
    </div>
  </header>

  <% if false %>
    <p>
      <%= link_to "Sign In", new_session_path %> or
      <%= link_to "Sign Up", new_user_path, class: 'btn btn-primary' %> today!
    </p>
  <% end %>