config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :wikis, :path => "notes"
  resources :contacts, only: [:new, :create]
  resources :charges, only: [:new, :create]
  resources :wikis do
    resources :collaborators, only: [:new, :create, :destroy]
    get :autocomplete_user_email, :on => :collection
    collection do
      get 'search'
    end
  end

  get 'downgrade' => 'users#downgrade'
  get 'about' => 'welcome#about'
  get 'home' => 'welcome#home'
  root to: "welcome#home"
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators
  validates :title, presence: true, length: {minimum: 1 }
  validates :body, presence: true

  def private?
    self.private == true
  end

  def self.find_view(user, wikis)
    @viewable_wikis = []
    wikis.each do |wiki|
      if (wiki.user == user || !wiki.private? || wiki.collaborators.include?(user))
        @viewable_wikis << wiki
      end
    end
  end

  def self.search(params)
    wikis = Wiki.where("title like ? or body like ?", "%#{params[:search]}%", "%#{params[:search]}%") if params[:search].present?
  end

  private

  def make_public
    self.private == false
  end

end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  require 'will_paginate/array'
  before_filter :authenticate_user!

  def index
    @wikis = policy_scope(Wiki.all.order("created_at DESC")).paginate(page: params[:page], per_page: 5)
    @user = current_user
  end

  def search
    @wikis = Wiki.search(params)
    @search = params[:search]
  end

  def show
    @wiki = Wiki.friendly.find(params[:id])
  end

  def new
    @wiki = Wiki.new
    @wiki.user = current_user
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user

    if @wiki.save
      flash[:notice] = "\"#{@wiki.title}\" was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the entry. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.friendly.find(params[:id])
    @users = User.all
    @collaborator = Collaborator.new
  end

  def update
    @wiki = Wiki.friendly.find(params[:id])

    @wiki.assign_attributes(wiki_params)
    @wiki.user_ids = params[:wiki][:user_ids] if params[:wiki][:user_ids].present?

    if @wiki.save
      flash[:notice] = "\"#{@wiki.title}\" has been updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error updating the entry. Please try again."
      render :edit
    end
  end

    def destroy
    @wiki = Wiki.friendly.find(params[:id])
    authorize @wiki

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" has been deleted."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :slug, :private, :user_id, :user_ids)
  end

end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/wikis/_form.html.erb
  <%= form_for [wiki] do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
    </div>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, rows: 8, class: 'form-control form-class', placeholder: "Enter wiki body" %>
    </div>
    <% if current_user.admin? || (current_user.premium? && current_user == wiki.user) %>
      <div class="form-group">
        <%= f.label :private, class: 'checkbox' do %>
          <%= f.check_box :private %>
          Private wiki
        <% end %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.submit "Save", class: 'save-btn' %>
    </div>
    <% if @wiki.private %>
      <%= render partial: 'collaborators/form', locals: { f: f } %>
    <% end %>
  <% end %>

  <script>tedmetrics.report('New note form');</script>

app/views/wikis/_wiki.html.erb
<div class="container">
  <% @wikis.each do |wiki| %>
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="author">
            <%= link_to wiki.title, wiki %> <% if wiki.private? %> <span class="private">private note</span> <% end %>
            <br>
            <small>
              submitted <%= time_ago_in_words(wiki.created_at) %> ago by <%= wiki.user.email %>
            </small>
            <hr>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/wikis/edit.html.erb
<h1>Edit note</h1>
<div class="row">
  <div class="col-md-4">
    <p>What's on your mind?</p>
    <p>Use the textbox to write about whatever you'd like:</p>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki  }%>
  </div>
</div>

<script>tedmetrics.report('Note edit form');</script>

app/views/wikis/index.html.erb
<h1 class="header">All notes
    <div class="btn"><%= link_to 'New note', new_wiki_path, class: 'btn-sm btn-success' %></div>
</h1>
<hr>
<br/>
<%= render partial: 'wiki', locals: { wiki: @wikis  }%>

<div class="pagination">
  <%= will_paginate @wikis, previous_label: "Older", next_label: "Newer", inner_window: 1, outer_window: 0 %>
</div>

<script>tedmetrics.report('index page loaded');</script>

app/views/wikis/new.html.erb
<h1>New note</h1>
<div class="row">
  <div class="col-md-4">
    <p>What's on your mind?</p>
    <p>Use the textbox to write about whatever you'd like!</p>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
  </div>
</div>

app/views/wikis/search.html.erb
<h2> Results for: <%= @search %> </h2>

<% @wikis.each do |wiki| %>
  <% if !wiki.private? %>
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="author">
            <%= link_to wiki.title, wiki %> <% if wiki.private? %> <span class="private">private note</span> <% end %>
            <br>
            <small>
              submitted <%= time_ago_in_words(wiki.created_at) %> ago by <%= wiki.user.email %>
            </small>
            <hr>
        </div>
      </div>
    </div>
  <% else %>
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="author">
          <h3>No results for this particular search.</h3>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/wikis/show.html.erb
<h1 class="header">
  <br>
  <%= @wiki.title %>
    <div class="button-group">
      <% if policy(@wiki).edit? %>
        <%= link_to "Edit", edit_wiki_path(@wiki), class: "btn-sm btn-success" %>
      <% end %>
      <% if policy(@wiki).destroy? %>
        <%= link_to "Delete", @wiki, method: :delete, class: 'btn-sm btn-danger', data: {confirm: 'Are you sure you want to delete this?'} %>
      <% end %>
    </div>
</h1>

<% if @wiki.private? %>
  <h5>This is a private note</h5>
<% end %>

<div class="row">
  <div class="col-md-8">
    <p>
      <%= markdown(@wiki.body) %>
    </p>
  </div>
</div>

<script>tedmetrics.report('note show page loaded');</script>